spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/LocalDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use `update` for development; change to `validate` or `none` in production.
    show-sql: true # Displays SQL queries in the console.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  
server:
  port: 9091
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
jwt:
  secret: LvrOHm1SEp5gCKzpuhNxVUl8jrSaE+0Z2PbyPMs0PzMQwoSueUgyVUwmI74Cd4onm3Dx4J8Ao+T4CTlvCoD8uQ==
  expiration: 86400000  # Token validity in milliseconds (1 day)
logging:  file:    name: user-service.log
    path: D:\JAVA-PRACTIVE\Microservice\logs\user-service.log